age=input("how old are you?")
print("my age is :{age}".format(age=age))
height=input("how tall are you?")
print("myheight is :{height}".format(height=height))
weight=input("how much do you weigh?")
print("my weight is :{weight}".format(weight=weight))