print("how old are you?")
age=input()
print("my age is :{age}".format(age=age ))
print("how tall are you?")
height=input()
print("my height is :{height}".format(height=height))
print("how much do you weigh")
weight=input()
print("my weight is :{weight}".format(weight=weight))